### ISSUE TITLE
工具优化计划

### ISSUE THREAD

**Issue by x2x4com** [itering/substrate-ops#4]
1. 支持单节点方式运行，既不用consul，只是单节点，如果节点不产块则自动重启(依旧基于Docker)
2. 优化节点方式，全部跑容器中去，采用建议最佳方式(输出文档)
3. 增加邮件报警功能，预留短信接口
4. 尝试节点异常时保存docker的日志信息

**Comment by freehere107** [comment]
现在节点已支持Prometheus ,https://prometheus.io/

**Comment by freehere107** [comment]
https://github.com/paritytech/substrate/blob/ebd4243487e6fbc7b19caab03a2759fa08285938/utils/prometheus/README.md

**Comment by freehere107** [comment]
https://substrate.dev/docs/en/next/tutorials/visualizing-node-metrics/

**Comment by freehere107** [comment]
有一些重启节点仍然不会同步块的情况，必须要删除db才能再次同步，但是可能会需要同步很久
